### ISSUE TITLE
angular可以用吗？

### ISSUE THREAD

**Issue by xxxx96923** [guozhaolong/wfd#10]

**Comment by guozhaolong** [comment]
angular1.0是我最早接触js框架时候用的，有内存泄漏的bug，后来用的react，然后发现angular2.0，用完发现就是在学react，后来用了vue因为react闹的短暂的收费事件造成国内一些甲方要求用vue，再后来又用回了react，因为更喜欢react的方式，实际做前端感觉vue或react都可以，但angular用的人实在太少了
