### ISSUE TITLE
大佬，我想扩展，做一个子流程的节点。G6 不支持在Group中添加 自定义node。有什么好的想法？

### ISSUE THREAD

**Issue by forbreak** [guozhaolong/wfd#20]
G6 不支持自定义的 group ，把 子流程当初一个node的话。 Group中又不支持 添加 node 和 edge。进行不下去了，你这边有没有啥好的建议？

**Comment by guozhaolong** [comment]
不用自定义group，直接自定义node就行，就类似node下面挂的那些anchor锚点，然后子流程下面的node和edge是子流程节点的属性

**Comment by guozhaolong** [comment]
这个子流程node需要可以展开和收缩，收缩的时候就是普通的一个节点，展开的时候，需要定位里面所有子节点的BoundRect来确定node的大小；然后子节点可以在里面移动，一旦添加子节点被加进去就不能拖出来了，外部节点和子流程节点中的子节点连线按照工作流的业务逻辑我觉得可以屏蔽掉

**Comment by guozhaolong** [comment]
还有个更傻的办法，就是你子流程节点就是普通的一个node，里面可以配置一个流程ID，想编辑子流程的话，设计器就打开子流程

**Comment by forbreak** [comment]
@guozhaolong 感想大佬回答。 昨天想的就是如果行不通就用双击子流程，设计器就加载子流程内部节点的方式处理。看了你上面说的，我打算再试试自定义node的方式实现，先研究研究看。

**Comment by guozhaolong** [comment]
嗯，我之前也是偷懒没做子流程节点，我有空也研究一下

**Comment by guozhaolong** [comment]
https://g6.antv.vision/zh/docs/manual/middle/nodeGroup
你看这个文档了么？感觉可以直接实现啊

**Comment by forbreak** [comment]
@guozhaolong   看过这个，但是这里面的group不受控，子流程需要连线，我们要加可以连线的瞄点。还想手动控制group大小。理论上如果可以自定义 group的话会比较好实现。

**Comment by guozhaolong** [comment]
@forbreak 我试了一下，如果想自定义node去实现特别麻烦，因为很多通用的内置和扩展功能如查找、复制、选择等，都是通过graph去找节点的，如果自定义node再添加子node就会造成graph找不到这些子node，在registerNode里面又无法找到graph；所以我感觉还是通过behavior去扩展他的group实现起来更简单一些

**Comment by forbreak** [comment]
@guozhaolong  我已经用自定义node实现了。麻烦是麻烦点，但是问题都不大，找不到节点的地方，先找到子流程的group然后在group里面搜索节点就好了。 改动的也不算多，我是copy了你的代码用angular 实现的。等我忙完这段，整理到react里面提交下代码。用group实现完全没思路，G6的事件好像没有group的事件，自定义样式，添加瞄点，改变大小这些需求都不止怎么处理。 文档上面group的说明太少了。我觉得 G6 官方要扩展Group出来，可能通过自定义Node 做一个会方便很多。很多东西都可以沿用node的，容易学习也方便扩展。现在的G6官方的那个 group真的用处太少了。

**Comment by guozhaolong** [comment]
@forbreak 好强啊，我试验了一下感觉用node实现相当于实现一个小型的canvas，好麻烦，兄弟后面分享出来学习一下啊
