### ISSUE TITLE
大牛，请问结点和连线支持点击事件吗？

### ISSUE THREAD

**Issue by zhuifeng00001** [guozhaolong/wfd#24]
1. 结点、连线是否支持鼠标点击事件。比如点击弹出页面，输入数据，然后提交后台。

2.左侧拖拽结点，是否支持纯文字的，树形菜单？

谢谢！

**Comment by guozhaolong** [comment]
点击事件和纯文字的节点都很好加，如果是个通用需求我可以加到代码里，或者你fork下代码自己改一下

**Comment by zhuifeng00001** [comment]
> 点击事件和纯文字的节点都很好加，如果是个通用需求我可以加到代码里，或者你fork下代码自己改一下

感谢回复!

当前看来文字树形菜单这种需求是次于图标的，看您能否提供下稍详细的修改思路呢？

之前尝试了GG-Editor，改造暂无结果，感觉没有您的这套灵活。

**Comment by guozhaolong** [comment]
点击弹出事件你可以参见behavior/clickSelected.js，纯文字节点需要你在shape/flowNode.js中自己添加一个自定义节点
