### ISSUE TITLE
拖拽的节点必须是img?

### ISSUE THREAD

**Issue by zhuifeng00001** [guozhaolong/wfd#25]
比如删除img，将自定义属性放在div上，但文字无法拖拽

`          
          <div data-item={"{clazz:'start',size:'30*30',label:''}"} >{i18n['startEvent']}</div>`

比较初级，希望指点一下

**Comment by guozhaolong** [comment]
只要是div上面有data-item属性即可，这个是通过plugins目录下面的addItemPanel.js去控制的，你可以看一下
