### ISSUE TITLE
大牛，项目是否支持IE11

### ISSUE THREAD

**Issue by liutao0218** [guozhaolong/wfd#27]
1.项目在chrome，Edge等运行正常，IE11界面直接报白，项目是否支持IE11？

谢谢！

**Comment by guozhaolong** [comment]
没试过IE啊。。。看看控制台报啥错啊

**Comment by liutao0218** [comment]
页面直接空白,
控制台打印信息：
SCRIPT1002: 语法错误
umi.js (34478,99462)

我猜测应该是IE 11不支持新的JS写法，需要引入babel-polyfill在测试下..

**Comment by guozhaolong** [comment]
我知道了，这是因为umi的问题，直接build出来是没问题的，目前umi也没有别的办法
