### ISSUE TITLE
安装部署依赖项找不到，需要手动拷文件进来

### ISSUE THREAD

**Issue by tobbygit** [guozhaolong/wfd#29]
node_modules\wfd\dist\index.esm.js:2:15: Cannot resolve dependency '@antv/g6/src'

**Comment by guozhaolong** [comment]
你这个是因为g6升级版本以后没有src这个目录了，我把package.json的g6版本先锁到老版本了，等我升级完就可以了

**Comment by pkaq** [comment]
@guozhaolong 
3.5.2也不行, 把packjson.json里用到的依赖都复制到项目里了 依然报错
```

These dependencies were not found:

* @antv/g6/src in ./node_modules/wfd/dist/index.esm.js
* @antv/g6/src/item/item in ./node_modules/wfd/dist/index.esm.js
* @antv/g6/src/shape/single-shape-mixin in ./node_modules/wfd/dist/index.esm.js
```

**Comment by guozhaolong** [comment]
你把你的node_modules删了重新安一下试试

**Comment by mengmengchichi** [comment]
我重装了多次还是报上面那个错，找不到资源，看node_modules里面g6都没有src的目录

**Comment by guozhaolong** [comment]
你代码没更新吧，后来升级版本更新了代码不再用src目录了啊

**Comment by pkaq** [comment]
> 你代码没更新吧，后来升级版本更新了代码不再用src目录了啊

https://github.com/guozhaolong/wfd/blob/1.0.11/src/index.js

有的

**Comment by guozhaolong** [comment]
你把分支切到master上面，不要在release的1.0.11上面，因为master更新了代码和包但是没有发布新的版本

**Comment by pkaq** [comment]
> 你把分支切到master上面，不要在release的1.0.11上面，因为master更新了代码和包但是没有发布新的版本

npm下下来的不是啊.......难道要人肉拷贝源码使用的吗......

**Comment by guozhaolong** [comment]
我之前打包的代码由于package.json里面没有限制死g6版本导致的，毕竟这项目想直接用在自己的项目里有点难啊，都是下源码自己改造的

**Comment by Jiang-boyang** [comment]
> 我之前打包的代码由于package.json里面没有限制死g6版本导致的，毕竟这项目想直接用在自己的项目里有点难啊，都是下源码自己改造的
但是既然之前有npm的包，还是更新下继续用比较方便吧？我现在拉master的代码，build之后推送到私有仓库，在下载回来用的...
