### ISSUE TITLE
最新的G6直接把shape去掉了，不暴露出来了。现在如何支持最新的g6，是否考虑后续迁移x6？

### ISSUE THREAD

**Issue by forbreak** [guozhaolong/wfd#32]
G6直接把shape去掉了。现在升级就gg。我用了g2 升级g2的话 辅助包就升级了，g6就也用不了。郁闷。锁版本要把g2和g6一起锁了才行，吐槽下。。。
大神，弱弱的问一下。你计划接下来怎么弄？ 继续使用g6，还是使用后面开源的x6？ x6正式版也不知道什么时候可以出来？

**Comment by guozhaolong** [comment]
我已经升级到新版的g6了，没有暴露shape并不影响，你可以看我的dev分支，只不过目前g6有bug不支持一些拖拽事件

**Comment by forbreak** [comment]
学习了，原来可以直接引用lib里面的内容来用。
