### ISSUE TITLE
审批节点无法添加表单信息

### ISSUE THREAD

**Issue by GoldSubmarine** [guozhaolong/wfd#37]
相比于官方的modeler，好像少了很多属性，是遗漏了还是我需要集成其他插件呢？目前我的需求是要给审批节点添加form url

**Comment by guozhaolong** [comment]
你可以自己随意添加属性，然后更改一下节点detail配置，让节点能够配置更多的属性

**Comment by GoldSubmarine** [comment]
你是说直接改这个项目的代码吗？不知道后续你是否准备把这个库发布成npm包，如果是npm包的话，感觉还是提供api接口比较好

**Comment by guozhaolong** [comment]
这个已经发布成npm包了，只不过每个人的需求不一样，比如我这边的流程审批节点并没有form url地址，所以还是自己fork下来直接改比较方便

**Comment by GoldSubmarine** [comment]
react的props或vue的slot可以适用这种场景吗？改源码的方式就无法获取升级

**Comment by guozhaolong** [comment]
嗯，对比modeler确实少了很多节点和配置项，主要是我们项目的需求要精简flowable，所以后面会合并成几个简单的节点，如果你有需求只能自己改我的源码了。。。
