### ISSUE TITLE
大佬 ，项目启动报错

### ISSUE THREAD

**Issue by w503736805** [guozhaolong/wfd#4]
D:\wfd-master>umi dev
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'D:\wfd-master\pages'
    at fs.readdirSync (fs.js:904:18)

**Comment by guozhaolong** [comment]
在wfd-master/example目录下执行umi dev
