### ISSUE TITLE
this.graph.setItemState无法有效设置state

### ISSUE THREAD

**Issue by loongmxbt** [guozhaolong/wfd#42]
在更新wfd-vue到g6 3.5 时遇到的问题，然后到wfd中复查，发现也有此问题。

运行wfd时，behaviour事件无反应，经debug发现是this.graph.setItemState的问题
```js
onNodeMouseOver(e) {
      if (this.graph.getCurrentMode() === 'edit') {
        // this.graph.setItemState(e.item, 'hover', true); // 无法设置状态,hasState均为false
        e.item.setState('hover', true) // 可以设置状态 // hasState均为true
        console.log(e.item.hasState('hover'))
      } else {
        // this.graph.setItemState(e.item, 'hover', false);
        e.item.setState('hover', false)
      }
    },
```
改为e.item.setState() 就可以了。

"@antv/g6@~3.5.0":
  version "3.5.3"

![image](https://user-images.githubusercontent.com/5986600/84366247-24c62200-ac05-11ea-9b96-bc6c0b689696.png)

直接用的最新wfd repo，yarn运行的，有人遇到同样问题么？

**Comment by guozhaolong** [comment]
看了一下G6源码，不应该有这个问题啊

**Comment by loongmxbt** [comment]
我想知道只有我一人在wfd项目下这样么。请问您那里运行项目有这个问题么？
我的操作是
npm run build
npm run dev
yarn和npm都试过了，应该不是包管理器的问题。
https://www.loom.com/share/db4122802fe846ec96144965cfdbba4c

**Comment by guozhaolong** [comment]
我这没问题啊，刚又试了一下

**Comment by guozhaolong** [comment]
我发现问题了，好像g6到3.5.2就不行了

**Comment by guozhaolong** [comment]
我这边测出问题了，应该是G6版本3.5.3的bug，3.5.0和3.5.2都没，换成3.5.3就不行

**Comment by guozhaolong** [comment]
https://github.com/antvis/G6/issues/1661#issue-636393136

**Comment by loongmxbt** [comment]
3.5.4 拖拽连线好像还是有问题，3.5.2没问题，目前先退回3.5.2，等之后再看看。

**Comment by guozhaolong** [comment]
对，3.5.4那里对于自己创建的anchor的setItemState好像是不好使的，他的graph.setItemState好像只对于Node和Edge生效
