### ISSUE TITLE
111

### ISSUE THREAD

**Issue by xiano5** [guozhaolong/wfd#44]

**Comment by guozhaolong** [comment]
额。。。咋了啊

**Comment by guozhaolong** [comment]
不知道哪里惹到兄弟了。。。代码有地方确实写的不好，我已经在新版本里慢慢修正了

**Comment by xiano5** [comment]
没有 发错了 哥

**Comment by xiano5** [comment]
> 不知道哪里惹到兄弟了。。。代码有地方确实写的不好，我已经在新版本里慢慢修正了
没有 发错了 哥

**Comment by xiano5** [comment]
顺便问一下  你这个创建自定义node  是在哪创建的   shape文件吗

**Comment by xiano5** [comment]
> 不知道哪里惹到兄弟了。。。代码有地方确实写的不好，我已经在新版本里慢慢修正了

顺便问一下 你这个创建自定义node 是在哪创建的 shape文件吗

**Comment by guozhaolong** [comment]
就在node.ts的drawShape方法

**Comment by xiano5** [comment]
> 就在node.ts的drawShape方法

谢了 哥
