### ISSUE TITLE
如何获取和设置流程标识？

### ISSUE THREAD

**Issue by Nayacco** [guozhaolong/wfd#45]
![image](https://user-images.githubusercontent.com/22909744/85923750-4b03e700-b8c0-11ea-854f-8e276ae7a829.png)

设置流程的标识后，调用 save 方法，获取到的json中没有流程的信息，是否是bug？

另外再次编辑时，如何把流程标识的信息设置上，readme中貌似只可以设置节点

**Comment by Nayacco** [comment]
我用的 vue 版
看了下源码，貌似要通过 this.$refs['wfd'].processModel 获取，但是这不太符合组件隔离的原则，要读源码才能知道怎么取，还是应该通过api暴露出来的，包括this.$refs['wfd'].graph.save() 方法，最好多包一层，改为 this.$refs['wfd'].save()

**Comment by guozhaolong** [comment]
嗯，这块是我忘记写代码了，多谢兄台提醒，后面会改正

**Comment by Nayacco** [comment]
我想增加一个保存图片的方法，this.$refs['wfd'].graph.saveImg()，直接canvas转图片会有白边，需要优化一下才能去白边，所以想把这个功能也集成在这个项目里，如果提 PR 的话，不知道你是否会接受？

**Comment by guozhaolong** [comment]
没问题，不过我要测一下，之前一哥们提的subprocess子流程结果出了一些bug
