### ISSUE TITLE
请教大佬，想增加显示类似echarts图表的节点应该怎么实现？

### ISSUE THREAD

**Issue by wrh4585** [guozhaolong/wfd#47]
请教大佬，想增加显示类似echarts图表的节点应该怎么实现？目前使用自定义dom节点的方式，无法成功的增加类似于echarts这样的图表，大佬是否有考虑过增加此类型的实现？也就是说在节点中，显示echarts，感觉上不难，实际上实现就比较困难！请教下大佬，如果要实现此类的功能，应该怎么实现。

**Comment by guozhaolong** [comment]
大部分的chart图组件都是要render到html的一个dom节点上的，我觉得你用antv的g2就可以做到吧，echarts应该问题不大，主要看echarts的包怎么引进来，我没用过dom节点，有官方的例子吗

**Comment by wrh4585** [comment]
> 大部分的chart图组件都是要render到html的一个dom节点上的，我觉得你用antv的g2就可以做到吧，echarts应该问题不大，主要看echarts的包怎么引进来，我没用过dom节点，有官方的例子吗

使用echarts的自定义dom节点，可以在初始化的时候正常显示图表，但是不支持节点的拖动等事件，拖动时会将echarts渲染图表的canvas从element元素中删除，倒是节点内容为空。。。

**Comment by guozhaolong** [comment]
我正在忙，等抽空我看一下

**Comment by wrh4585** [comment]
官方的自定义dom节点的例子中，没有对这种类似于echarts的图表的示例，从源码中看，可能是在交互行为时获取了所有的canvas，然后统一做了清空画布的操作。

请教下，大佬做这个项目时，所以的节点都是通过自定义注册的，是否可以自定义一下锚点的显示位置，如对于某些特定类型的节点，显示在节点的内部？是在shape文件夹下的anchor.js中进行配置吧。
您先忙您的，我这边不着急，主要也是请教学习下，大佬的项目已经给我许多启发了。

**Comment by baizn** [comment]
G6 现在支持自定义图表节点了，可以将统计图表作为节点的一部分，具体DEMO 可以看这里  https://g6.antv.vision/zh/examples/item/customNode#intervalChartNode
