### ISSUE TITLE
怎样增加节点的拖拽缩放功能？

### ISSUE THREAD

**Issue by wrh4585** [guozhaolong/wfd#48]
请教大佬，怎样增加节点的拖拽缩放功能？
考虑通过一个事件如节点的双击事件，使得节点可以通过拖拽控制节点的大小？这个功能应该怎么实现呢？

**Comment by guozhaolong** [comment]
可以在节点右下角增加一个类似textarea的resize图标之类的shape，然后就像anchor一样配置item和拖拽事件即可

**Comment by wrh4585** [comment]
> 可以在节点右下角增加一个类似textarea的resize图标之类的shape，然后就像anchor一样配置item和拖拽事件即可

好的，谢谢大佬的思路，我去试下具体的实现。

**Comment by wrh4585** [comment]
大佬，请教下，我仿照anchor在节点group增加了一个拖拽的节点的图标，添加了事件，拖拽这个图标的时候，对这个图标外层的大包围盒子也就是真实需要拖拽放大的节点改变大小（width、height），即调用graph.updateItem,和graph.refreshItem方法,但是视图不发生变化，拖拽完毕后，点击节点在控制台打印节点的数据，可以看到节点的属性是发生了变化的。两者数据model的区别就是拖拽后的model里有width、height属性，原来的没有。而且size属性的值没有变化，是否是因为size属性的原因？导致了更新节点的操作没有生效

**Comment by guozhaolong** [comment]
Duplicate of #50 

通过shape.attr(style)可以解决，这里我也没仔细看G6源码，应该是属性虽然改了并没有重绘shape，下面是G6源码的updateItem，有时间可以看一下
![image](https://user-images.githubusercontent.com/1046601/88528243-f2477b80-d030-11ea-9b54-c1263140cb5d.png)

**Comment by wrh4585** [comment]
好的，谢谢大佬，我试试去。
