### ISSUE TITLE
大佬，请教下，关于toFront()/toBack()方法

### ISSUE THREAD

**Issue by wrh4585** [guozhaolong/wfd#53]
关于toFront()/toBack()方法，在节点调用这两个方法的时候，是直接将选中的节点置为顶层或者底层了。有什么方法可以使节点每次只移动一层？
比如有三个节点，A，B，C,如图。选中B节点调用toBack()方法，B节点视觉上位于A,C节点的下方，但是在调用toFront()方法后，B节点会位于A,C节点的上方，怎么做才能才能时B向上移动一层而不是直接移动到顶层？
![image](https://user-images.githubusercontent.com/45685551/90225434-f3a3e100-de43-11ea-9f84-cf8d900fbef4.png)

**Comment by guozhaolong** [comment]
我看了一下源码，G6是通过zIndex属性去排序的，设置完新的zIndex然后执行sort()即可
![image](https://user-images.githubusercontent.com/1046601/90233715-20122a00-de51-11ea-8a13-7afcefc0a5f8.png)

**Comment by wrh4585** [comment]
好的，谢谢大佬。
这个图片是源码的截图么，网页显示不出来呢？
我去看看G6的源码，熟悉下这块。
