### ISSUE TITLE
请教一下，添加节点时要选择数据源。这个操作怎么实现？

### ISSUE THREAD

**Issue by wrh4585** [guozhaolong/wfd#55]
请教大佬，添加节点（部分节点需要后台数据）时要选择数据源（类似于弹框选择数据来源等）。这个操作怎么实现？
在dragPanelItemAddNode.js中判断进行判断（给需要数据的节点添加了标识），然后对对应节点进行数据的添加，使用element-ui的弹框，数据选择时使用树状表格。

**Comment by guozhaolong** [comment]
你可以在dragEnd的时候触发this.graph.emit('自定义事件'),然后在index.tsx中this.graph.on('自定义事件')监听然后弹出框去显示属性数据源，和展示node的详情一个道理

**Comment by wrh4585** [comment]
好的，谢谢大佬提供的思路。
我这边用的是vue，我在添加节点的时候，判断节点的类型，将需要数据源的节点记录到了vuex中，然后在引用wfd组件的地方监听记录在vuex中的变化，已经可以弹出弹框了。不过，还存在其他业务功能上的影响。
