### ISSUE TITLE
save方法的问题

### ISSUE THREAD

**Issue by wrh4585** [guozhaolong/wfd#57]
save方法的问题。我改变了节点的图片，然后预览时调用save()方法，但是预览的节点现实的图片还是改变前的图片，感觉是更换了图片但是没有检测到数据的变化，节点使用的是group中包裹的image。点击更换了图片的节点，查看时image节点的值没有改变。大佬有什么好的方法解决这个问题呢？

**Comment by guozhaolong** [comment]
image节点是啥啊？是有个node里面的属性是个图片的url么？

**Comment by wrh4585** [comment]
是的，我是在节点的group里children中看到的。这个问题应该是save方法只能把节点的model数据保存，但是此时图片的并不在 model里。所以更换了图片，调用save方法数据没有变化。

**Comment by wrh4585** [comment]
G6更新到3.7.0版本后，可以使用G2的图表了。我参照之前注册节点的方法，注册了一个使用折线图的节点。
`// 尝试使用G6中自定义的G2图表节点
  G6.registerNode('use-g2-charts-node', {
    shapeType: 'rect',
    labelPosition: 'bottom',
    options: {
      ...chartsDefaultOptions
    },
    draw(cfg, group) {
      const keyShape = group.addShape('rect', {
        attrs: {
          x: 0,
          y: 0,
          width: 400,
          height: 200,
          fill: 'cyan',
        },
      });

      group.addShape('rect', {
        attrs: {
          x: 0,
          y: 0,
          width: 400,
          height: 40,
          fill: '#69c0ff',
        },
      });

      group.addShape('text', {
        attrs: {
          text: '浏览申请完成率',
          x: 10,
          y: 25,
          fontSize: 14,
          fill: '#fff',
        },
      });

      group.addShape('text', {
        attrs: {
          text: '2020-06-07 ~ 2020-06-14 | 均值',
          x: 20,
          y: 70,
          fontSize: 13,
          fill: '#8c8c8c',
        },
      });

      group.addShape('text', {
        attrs: {
          text: '8.8%',
          x: 20,
          y: 110,
          fontSize: 30,
          fill: '#000',
        },
      });

      // 实际开发中把 (Chart || window.Chart) 换成 Chart
      // Replace (Chart || window.Chart) by Chart in your project
      const view = new Chart({
        group,
        padding: 5,
        width: 360,
        height: 70,
        x: 20,
        y: 100
      });
      const trendData = [{
          genre: 'Sports',
          sold: 275
        },
        {
          genre: 'Strategy',
          sold: 115
        },
        {
          genre: 'Action',
          sold: 120
        },
        {
          genre: 'Shooter',
          sold: 350
        },
        {
          genre: 'Other',
          sold: 150
        },
      ];
      view.data(cfg.trendData ? cfg.trendData : trendData);

      view.line().position('genre*sold').color('#9AD681').shape('dash');

      view.legend('genre', false);

      view.axis('sold', false);

      view.render();

      return keyShape;
    },
    afterDraw(cfg, group) {
      this.runAnimate(cfg, group)
    },
    // update: null,
  }, 'basic-node')`
页面上可以渲染出来，但是存在报错，节点的选中判断和锚点的判断有问题。
请教下大佬，类似于这种的节点，需要怎么修改，才能达到正常使用的效果？

**Comment by guozhaolong** [comment]
你把报错信息发上来啊，这玩意新加的我也没用过

**Comment by wrh4585** [comment]
不好意思，最近一忙就忘记了，这个问题是G6官方的svg引擎的问题。在初始化G6的graph时，有自定义节点的需要加上
renderer: 'svg'
