### ISSUE TITLE
求教大佬，将项目中G6的渲染方式变为svg后，不能动态增加边

### ISSUE THREAD

**Issue by wrh4585** [guozhaolong/wfd#61]
求教大佬，将项目中G6的渲染方式变为svg后，不能动态增加边！！！
在初始化G6的graph时，将渲染方式改为svg，即增加renderer:'svg'后，从锚点上拖动新的连线失败，请问下这个怎么解决？
试了下，react版本的也是一样的，但是G6官方的示例中改为svg的渲染方式，拖拽增加边的示例还是正常的。
对于这块边的实现，不熟悉，所以求教大佬。

**Comment by guozhaolong** [comment]
我有空看一下，最近在忙应用设计器这块，没咋看g6

**Comment by wrh4585** [comment]
嗯嗯，多谢大佬，我这两天需要解决这个，如果解决了，我把方案贴出来。

**Comment by wrh4585** [comment]
目前已经解决。
造成的原因是，使用自定义的DOM节点，必须使用svg的渲染方式，但是G6的svg图中，对于onDragEnter事件不能触发，所以导致边在绘制时无法完成。
经过多方尝试，可以再dragEdge.js中增加一个onDragOver 事件，实现和 onDragEnter 事件基本一致，就可以解决svg渲染方式下，不能添加边的问题。
但还是存在一点小问题，onDragOver 事件不能像onDragEnter事件一样区分是否进入到anchor内部，所以会造成凡移动到anchor上方均会使其改变状态

**Comment by guozhaolong** [comment]
onDragOver事件应该是设置到anchor上面吧？当有拖拽经过anchor时触发

**Comment by wrh4585** [comment]
是的，我这边是vue的版本，dragEdge.js文件中定义的事件，是作用在anchor上的。
![image](https://user-images.githubusercontent.com/45685551/93414020-0f7f2480-f8d3-11ea-99cf-38bcc35871aa.png)

**Comment by guozhaolong** [comment]
无法区分是否进入到anchor内部是什么意思？

**Comment by wrh4585** [comment]
> 无法区分是否进入到anchor内部是什么意思？

onDragEnter事件在进入到anchor里时触发，移出anchor时不触发，但是onDragOver 事件，我这边试了，凡是拖拽箭头经过anchor都会触发，造成这样的效果：
![image](https://user-images.githubusercontent.com/45685551/93417212-0e9dc100-f8da-11ea-997d-96fa4226125e.png)
而onDragEnter事件，每次只会有一个anchor设置了Hotspot状态。
时间关系，没有细致的修改方法。毕竟连不上去线直接影响到功能了
