### ISSUE TITLE
请问大佬您的节点坐标是如何确定的？

### ISSUE THREAD

**Issue by Superzzw1994** [guozhaolong/wfd#64]
请问大佬，节点的x,y是相对于画布原点的x,y吗？鼠标相对于页面的clientX,clientY和dom节点到页面的left和top怎么菜能转化为画布上的坐标呢？如果画布拖动的话，坐标是如何计算的？
我现在用的是鼠标抬起时的clientX,clientY,通过G6提供的getPointByClient， getCanvasByPoint方法转化成canvasXY，但是位置错乱。
<img width="1439" alt="WeChatd56f00129f3edceb492168d12e06dab5" src="https://user-images.githubusercontent.com/20533727/96673268-b5252800-1398-11eb-8ae8-9b1f15e386b5.png">

**Comment by guozhaolong** [comment]
![image](https://user-images.githubusercontent.com/1046601/96688236-82d4f400-13b3-11eb-814a-689dffb7d5c7.png)
我就是用的getPointByClient，再减去node的长宽

**Comment by Superzzw1994** [comment]
我是生成了一个dom挂载在body下，然后在画布上mouseUp的时候获取鼠标此时的clientX，clientY，然后根据这个clientX,clientY去计算canvas节点的坐标，这样您看可行吗？我现在遇到的问题是，鼠标抬起后，我自定义节点的x,y是相对于我鼠标抬起点进行定位的，我实在是找不到原因了0.0

**Comment by guozhaolong** [comment]
你代码发上来看看，你目前的需求跟wfd里面那个拖拽增加节点的功能有啥区别吗？你说的dom挂载到body下是啥意思啊？不太明白

**Comment by Superzzw1994** [comment]
没有区别，我实现的思路跟您不一样，我上传一下，麻烦您了0.0 
https://github.com/Superzzw1994/graph
