### ISSUE TITLE
项目很棒，提一个小建议

### ISSUE THREAD

**Issue by johnnylc** [guozhaolong/wfd#7]
项目很精致，逻辑也很顺畅，费心了。
不过提一个小建议，试用后感觉业务耦合有些过于紧密，实际应用中可能不够灵活，不知有没有发布简化版的计划。将数据、业务逻辑和具体渲染拆分，比如为itempanel和canvas展示提供配置化的node基础信息，节点绘制后，节点通过逻辑接口决定toolbar，contextmenu的渲染内容，节点点击后提供回调函数决定detailpanel的渲染，等等。这样的话项目可能能更方便的应用于各个场景，而项目维护也可以更专注于工作流的渲染与编辑交互上，将具体业务的渲染和业务逻辑解放出来。

**Comment by guozhaolong** [comment]
好的，我在休假呢，回国后琢磨一下，这项目起初就是用于公司的工作流设计器，公司工作流引擎选型是flowable所以画了几个flowable中的图形包括属性配置也都是flowable的
