### ISSUE TITLE
会考虑提供vue版吗？

### ISSUE THREAD

**Issue by locxiang** [guozhaolong/wfd#8]

**Comment by guozhaolong** [comment]
有精力我就搞一个，逻辑代码是通用的，只是最外面的展现层要重写一个，应该很快能实现

**Comment by locxiang** [comment]
好的，非常期待

**Comment by guozhaolong** [comment]
vue地址：https://github.com/guozhaolong/wfd-vue
npm包发布还没搞定，目前只能直接用源码引用。。。
