### ISSUE TITLE
强烈建议弄一个vue版本

### ISSUE THREAD

**Issue by a-tony** [guozhaolong/wfd#9]
大佬，你这个编辑器，简洁明了直观，很给力，但是强烈建议支持vue，因为现在国内用vue的太多了，越来越多的人用vue

**Comment by guozhaolong** [comment]
好的，有精力就写一个vue的版本，现在精力集中在开发应用设计器上

**Comment by a-tony** [comment]
期待你的vue版本

**Comment by AK081KA** [comment]
大佬加油

**Comment by guozhaolong** [comment]
vue地址：https://github.com/guozhaolong/wfd-vue
npm包发布还没搞定，目前只能直接用源码引用。。。

**Comment by 13029678009** [comment]
强烈建议vue版本连接放在README里面，自己照着大佬的这个改了一个vue版本，绕了一圈，才发现有vue版本的，再看看我的代码。。。。。

**Comment by guozhaolong** [comment]
哈哈，好的
